# Generated by Django 4.0.2 on 2022-03-10 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image_delete_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='ids',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
