# Generated by Django 4.0.2 on 2022-03-10 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_image_id_image_file_name_image_flag_image_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ),
    ]
