# Generated by Django 4.0.2 on 2022-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_image_user_image_user_id_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
    ]
