# Generated by Django 4.0.2 on 2022-04-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
